name: heart_disease_prediction
description: A Flutter app for heart disease prediction using AI and blockchain technology.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Blockchain & Web3
  web3dart: ^2.7.2
  eth_sig_util: ^0.0.9
  crypto: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: 11.1.2
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # File handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true 