<?php
// Start session
session_start();

// Required files
require_once dirname(__DIR__) . '/config.php';

// Check if user is logged in
if (!isset($_SESSION['user'])) {
    http_response_code(401);
    echo 'Unauthorized access';
    exit;
}

$user = $_SESSION['user'];
$startDate = $_GET['start'] ?? date('Y-m-d', strtotime('-30 days'));
$endDate = $_GET['end'] ?? date('Y-m-d');
$format = strtolower($_GET['format'] ?? 'csv');

// Only admin and developer roles can export all data
$isAdmin = in_array($user['role'], ['admin', 'developer']);

try {
    // Build query based on user role
    if ($isAdmin) {
        $sql = "SELECT 
                    u.username, 
                    u.email, 
                    u.role,
                    p.created_at, 
                    p.age, 
                    p.sex, 
                    p.cp, 
                    p.trestbps, 
                    p.chol, 
                    p.fbs, 
                    p.restecg, 
                    p.thalach, 
                    p.exang, 
                    p.oldpeak, 
                    p.slope, 
                    p.ca, 
                    p.thal, 
                    p.prediction_result,
                    p.confidence_score,
                    CASE 
                        WHEN p.verified_by_expert = 1 THEN 'Yes' 
                        ELSE 'No' 
                    END as expert_verified
                FROM predictions p
                JOIN users u ON p.user_id = u.id
                WHERE DATE(p.created_at) BETWEEN ? AND ?
                ORDER BY p.created_at DESC";
        $params = [$startDate, $endDate];
    } else {
        $sql = "SELECT 
                    p.created_at, 
                    p.age, 
                    p.sex, 
                    p.cp, 
                    p.trestbps, 
                    p.chol, 
                    p.fbs, 
                    p.restecg, 
                    p.thalach, 
                    p.exang, 
                    p.oldpeak, 
                    p.slope, 
                    p.ca, 
                    p.thal, 
                    p.prediction_result,
                    p.confidence_score,
                    CASE 
                        WHEN p.verified_by_expert = 1 THEN 'Yes' 
                        ELSE 'No' 
                    END as expert_verified
                FROM predictions p
                WHERE p.user_id = ? AND DATE(p.created_at) BETWEEN ? AND ?
                ORDER BY p.created_at DESC";
        $params = [$user['id'], $startDate, $endDate];
    }
    
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Get headers from first row
    $headers = $data && count($data) > 0 ? array_keys($data[0]) : [];
    
    // Set filename
    $filename = 'heart_disease_report_' . date('Y-m-d') . '.' . $format;
    
    // Handle different export formats
    switch ($format) {
        case 'json':
            // Set headers for JSON download
            header('Content-Type: application/json');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            
            // Format the data
            $output = [
                'report_info' => [
                    'generated_at' => date('Y-m-d H:i:s'),
                    'start_date' => $startDate,
                    'end_date' => $endDate,
                    'generated_by' => $user['username']
                ],
                'data' => $data
            ];
            
            echo json_encode($output, JSON_PRETTY_PRINT);
            break;
            
        case 'csv':
        default:
            // Set headers for CSV download
            header('Content-Type: text/csv');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            
            // Open output stream
            $output = fopen('php://output', 'w');
            
            // Add report info as comments
            fputcsv($output, ['# Heart Disease Prediction Report']);
            fputcsv($output, ['# Generated: ' . date('Y-m-d H:i:s')]);
            fputcsv($output, ['# Period: ' . $startDate . ' to ' . $endDate]);
            fputcsv($output, ['# Generated by: ' . $user['username']]);
            fputcsv($output, ['# ']);
            
            // Add headers
            if (!empty($headers)) {
                fputcsv($output, $headers);
            }
            
            // Add data rows
            foreach ($data as $row) {
                fputcsv($output, $row);
            }
            
            fclose($output);
            break;
    }
    
} catch (PDOException $e) {
    // If there's an error, return plain text error
    header('Content-Type: text/plain');
    echo 'Error generating report: ' . $e->getMessage();
}
exit; 